server:
  port: 8001
spring:
  application:
    name: user-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: user-service

