server:
  port: 8001
spring:
  application:
    name: user-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    consul:
      discovery:
        hostname: localhost
        port: 8500
        health-check-interval: 15s

