server:
  port: 8001
spring:
  application:
    name: user-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    consul:
      host: localhost
      port: 8500
      enabled: true
      discovery:
        health-check-interval: 15s


